### ISSUE TITLE
Customization variables in `custom.el` are overwritten

### ISSUE THREAD

**Issue by bryce-carson** [SystemCrafters/rational-emacs#113]
The work in #112 introduced a bug that _overwrites_ the customization variables saved to `custom.el` by the Customizaiton UI. Further, 

The `rational-load-custom-file` function documentation (quoted below),
>  Load the `custom-file` after saving customized values. Customized values set during the initialization process are saved, other values set through the Customization UI or via certain workflows are not lost in this process. The `custom-file` is loaded last.

implies that the variables customized by `early-init.el` and `init.el` are saved to `custom.el`, which does not appear to be the case. The function `(customize-save-customized)` eventually calls `custom-save-delete` before reinserting the form into `custom.el`. As the values are customized outside of custom, they are not saved and are in fact deleted, along with any values set _**and**_ saved into `custom.el` by the Customization UI, as this deletion of the saved contents of `custom.el` occurs every initialization, exactly *when* we are trying to load previously customized variables.

I haven't understood why, but my incoming refactor *does* allow the customizations set outside of custom by `early-init.el` and `init.el` to persist in `custom-file`, along with customizations applied with the UI. As far am able to understand, the culprit is `custom-save-customized` calling `custom-save-delete` eventually.

I read *most* of the discussion around customization, and I'm in agreement with most things. One thing, however, is that I don't think we need a dedicated function to load the custom file. In my refactor I inlined the function into a lambda in the load call.

Using Rational has made me learn more about Emacs, mostly **Customization UI** ironically, even though the project isn't urging people to use it. I ended up using it a decent bit because it was a nice way to explore the Rational customization group without focusing on implementation; it was also how I learned to customize the fringe face, which I protected in code in my `config.el` until I wrote the refactor and fixed the regression.

🤷🏼 I'm not sure what Rational is going to do going forward, but I'm fairly sure I've fixed this.

**Comment by jeffbowman** [comment]
I tested several ways to make sure that didn't happen ... bummer ! (facepalm!!)

`custom-save-delete` only deletes the values out of the buffer. It depends on them already being set beforehand. If they aren't, then they disappear, which is not intended (aka "bad"). Ultimately, we don't really _need_ to call `customize-save-customized` at all, that was an attempt to get the currently customized values set during initialization stored in the `custom-set-variables` form. Your refactor works because it _doesn't_ save the customized values (which is fine, they are in the "SET but not saved" state), and then we load the values set through the Customize UI, via Org Mode Agenda file manipulation, and/or from  `.dir-locals.el` settings (ie, pressing the `!` to accept and remember the settings (see discussion in #111). In the end, all we need to do is remove the call to `customize-save-customized` and add your better wording in the README.org. 

We don't technically need to load the file in the `after-init-hook`, but that seemed like a reasonable place to put it so a user could choose to remove that from the hook if they don't want the `custom-file` loaded at all. The only (minor/nit picky) issue I have with your refactor is the use of `lambda` in the `after-init-hook` which makes it difficult to undo later. 

Would you mind updating your PR to only remove the call to `customized-save-customized`? (I've added some review notes)

Thanks very much, great catch!
