### ISSUE TITLE
Don't use advice-add or defadvice

### ISSUE THREAD

**Issue by theophilusx** [SystemCrafters/rational-emacs#124]
Although a very useful feature when no other option is available, the general advice from Emacs developers is to avoid advice-add or the older defadvice forms. In addition to contributing to some subtle bugs and obscuring the code, these forms also don't work well with lexical binding. 

In the rational-defaults.el module, we have the following 

```
(if (boundp 'use-short-answers)
    (setq use-short-answers t)
  (advice-add 'yes-or-no-p :override #'y-or-n-p))

```
The advice-add can easily be replaced with 

```
(if (boundp 'use-short-answers)
    (setq use-short-answers t)
  (fset 'yes-or-no-p 'y-or-n-p))

```

**Comment by jeffbowman** [comment]
We are avoiding `fset` in this case because it is difficult (impossible?) to reverse. Should a user prefer the long answers (yes vs y), this configuration would make it very difficult to go back to using `yes-or-no-p` (see #54)

In this case, if you use `fset` and then in the users `config.el` try to undo it like this: `(fset 'y-or-n-p 'yes-or-no-p)` it doesn't work like you expect. Instead you get this error in `*Messages*`:

```
Symbol’s chain of function indirections contains a loop: y-or-n-p
```

See the comment with this code, it describes how to reverse this decision by removing the advice. 

I'm open to other solutions that allow a user to reverse this decision.

**Comment by jeffbowman** [comment]
Closing, since there is no discussion since April.
