### ISSUE TITLE
rational ide module

### ISSUE THREAD

**Issue by HumHongeKamyaab** [SystemCrafters/rational-emacs#64]
I think the prime purpose of emacs is to use it as a modern IDE. It would greatly help the community if this project could provide a minimal module like a framework for different programming languages by integrating [eglot](https://github.com/joaotavora/eglot) (or [lsp](https://github.com/emacs-lsp/lsp-mode)), [yaspinnet](https://github.com/joaotavora/yasnippet), [company mode](https://github.com/company-mode/company-mode), and flymake. 

[Doom Emacs](https://github.com/hlissner/doom-emacs) and [Spacemacs](https://github.com/syl20bnr/spacemacs) already try to do it using layering. However, it is still confusing, and snippets from these projects can't be integrated into user configs easily, which is the best part of the rational emacs project.

**Comment by jeastman** [comment]
Before we touch on the specific packages to integrate (`company mode` could be replaced with [corfu](https://github.com/minad/corfu) which could be argued to be more closely aligned with the Principles), let's define the functionality one would expect from a "modern IDE".

I am no expert when it comes to "modern IDE"s, but I suspect the beginning of that list would be:

- In-line completion while typing in source code
- Support for templates / abbreviation expansion
- Automatic verification / checking / compilation
- Automatic formatting to code standard
- Code overview tools (source outline, etc.)
- Complex refactoring support

The next decision is if these go into a single module, like `rational-ide` or are the specific features more generally applicable? Maybe we could try to align each specific feature into existing module as a first step and, failing that, decide on a more focused `rational-ide` module.

**Comment by jeastman** [comment]
The more I think about this, the more I think we need to answer the second question first... Should we have a `rational-ide` module?

**Comment by theophilusx** [comment]
I think it would be very useful to have a rational-ide module, but with a 'rational' twist. 

Emacs has amazing functionality built-in which many users don't even realise. There are lots of features/modes built-in which many users never even realise and many of the external packages which people add actually re-implement features which are already there (but often with a slightly different approach or which use slightly different terminology which makes them difficult to recognise. 

What I would like to see is a rational-ide which tries to create a modern IDE using just built-in modes/packages from Emacs and GNU ELPA (and maybe NONGNU ELPA). Where we do find it necessary to go with 'external' packages, prefer ones which also attempt to leverage as much as possible on built-in facilities. For example, eglot over lsp-mode, flymake over flycheck, project.el over projectile etc. 

To some extent, I would see rational-ide as a showcase of what you can do to create a modern IDE using Emacs' built-in functionality. Once we have this as a basis, we can then see what gaps we have and how to best fill them. Where possible, perhaps we also add helpers or small libraries to make built-in features easier to use. For example, use a built-in template solution rather than just add yasnippet, make better use of abbrev mode etc. 

There will be some situations where an external package offers a significantly better solution than anything built-in and that will be a challenging decision. For example, I'm not sure I can go back to Emacs' VC modes over magit. However, we can deal with those more difficult decisions later. 

I also think the above list of what should be in an IDE module is a good starting point.

**Comment by ajxn** [comment]
Emacs can do so much more then just being an IDE, but except for that.

I agree that the list @jeastman have made is a good start.  I also think that we should go as much as possible with with "core" Emacs extensions, as @theophilusx  writes.

I like the idea of Rational-emacs as a show case of what Emacs can do.  So in many ways some code that is commented in documentation and/or the default config is fines.  I had problems with that evil mode was activated per default.  I also had some problems with other software/fonts/icons that wasn't installed.

I am even ready to let Magit be something that is mentioned, but commented out, in preference for VC mode.

**Comment by HumHongeKamyaab** [comment]
any updates on this ...

**Comment by jeffbowman** [comment]
Nothing since Feb 26... 

PRs gratefully accepted :-)

Give it a shot! There are several people here (including myself) who would potentially review, comment and help you out as needed.
