### ISSUE TITLE
Strange theme, ui, font coloring

### ISSUE THREAD

**Issue by TDiazT** [SystemCrafters/rational-emacs#96]
After PR #87 , the coloring and display changed a bit (not to my particular liking) and I'm wondering what would be the best approach (a "rational" way) to having the previous display. Is this a OS X thing? Should I be setting a particular bg color in `early-config.el` or something else? 

Before it was looking like this: 
![image](https://user-images.githubusercontent.com/7966908/158087067-48d73c5b-39e9-4e85-9e0b-7b24be0bf57a.png)

It is currently looking like this (black strips on the sides and a deep blue color for the buffer's name):
![image](https://user-images.githubusercontent.com/7966908/158087022-43628f07-5527-4b39-b2c4-26b7ab52cb0d.png)

**Comment by jeffbowman** [comment]
As I'm sure you read in the PRs (#87 and #37) setting the background and foreground color overrode themes in weird and unsatisfactory ways. However, if you wish to keep that configuration, you can apply those in your own `early-config.el` file. The reason you might want to do it in `early-config.el` is because it is loaded before the frame is rendered, so the colors are applied and there is no "flash"  of one color then an update to the color after `init.el` loads. 

The original code replaced by #87 is this:

    (push '(background-color . "#232635") default-frame-alist)
    (push '(foreground-color . "#FFFFFF") default-frame-alist)

You can also try using different themes, also loaded in your `early-config.el` for similar reasons. 

The "rational way" in this case is to apply changes to your own `early-config.el` or `config.el` files located in the `rational-config-path`

If this answers your question sufficiently, feel free to close this issue. If not, please feel free to continue the discussion and we'll help as best we can.

**Comment by TDiazT** [comment]
👍  Yeah, I tried with `early-config.el` but wasn't really working. I'll keep trying and see how it goes. At least I now know I was doing it the "rational way" haha. Thanks !
